/*
 * btnmap.h
 *
 *  Created on: Oct 11, 2022
 *      Author: bhat
 */

#ifndef SRC_HW_MAP_H_
#define SRC_HW_MAP_H_

#include "xparameters.h"

#define TIMER_ID XPAR_AXI_TIMER_0_DEVICE_ID
#define TIMER_INTR XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_INTR

#define ENCODER_ID XPAR_AXI_GPIO_ENCODER_DEVICE_ID
#define ENCODER_INTR XPAR_MICROBLAZE_0_AXI_INTC_AXI_GPIO_ENCODER_IP2INTC_IRPT_INTR

#define BTN_ID XPAR_AXI_GPIO_BTN_DEVICE_ID
#define BTN_INTR XPAR_MICROBLAZE_0_AXI_INTC_AXI_GPIO_BTN_IP2INTC_IRPT_INTR

#define LED_ID XPAR_AXI_GPIO_LED_DEVICE_ID
#define RGB_LED_ID XPAR_AXI_GPIO_RGBLED_DEVICE_ID

#define LCD_GPIO_ID XPAR_SPI_DC_DEVICE_ID
#define LCD_SPI_ID XPAR_SPI_DEVICE_ID

#define RGB_L_OFFSET 3
#define RGB_R_OFFSET 0
#define RGB_BLUE_OFFSET 0
#define RGB_GREEN_OFFSET 1
#define RGB_RED_OFFSET 2

#define BTN_L_MASK 2
#define BTN_R_MASK 4
#define BTN_T_MASK 1
#define BTN_B_MASK 8

#define MIC_BASE_ADDR XPAR_MIC_BLOCK_STREAM_GRABBER_0_BASEADDR

#define PROFILER_TIMER_ID XPAR_AXI_TIMER_1_DEVICE_ID
#define PROFILER_TIMER_INTR XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_1_INTERRUPT_INTR

#endif /* SRC_HW_MAP_H_ */
